// script.js

document.addEventListener('DOMContentLoaded', () => {
    // --- Existing code for smooth scrolling and mobile navigation toggle (KEEP THIS) ---
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            document.querySelector(this.getAttribute('href')).scrollIntoView({
                behavior: 'smooth'
            });
            const navbarLinks = document.querySelector('.nav-links');
            const hamburgerMenu = document.getElementById('hamburger-menu');
            if (navbarLinks && navbarLinks.classList.contains('active')) {
                navbarLinks.classList.remove('active');
                if (hamburgerMenu) hamburgerMenu.classList.remove('active');
            }
        });
    });

    const hamburgerMenu = document.getElementById('hamburger-menu');
    const navbarLinks = document.querySelector('.nav-links');
    if (hamburgerMenu && navbarLinks) {
        hamburgerMenu.addEventListener('click', () => {
            navbarLinks.classList.toggle('active');
            hamburgerMenu.classList.toggle('active');
        });
    }

    // --- NEW FUNCTION TO CLEAR NUMBERS AND SET A PLACEHOLDER ---
    function resetNumbersToPlaceholder() {
        const allNumberCells = document.querySelectorAll(
            '.prize-number, .results-table.special-table tbody td, .results-table.consolation-table tbody td'
        );
        allNumberCells.forEach(cell => {
            cell.textContent = "-";
        });
    }

    // --- NEW FUNCTION FOR THE SLOW REVEAL EFFECT ---
    function slowReveal(elements, values, delay) {
        let i = 0;
        function revealNext() {
            if (i < elements.length) {
                elements[i].textContent = values[i];
                i++;
                setTimeout(revealNext, delay);
            }
        }
        revealNext();
    }

    // --- YOUR CUSTOM FUNCTION FOR UPDATING DRAW NUMBERS ---
    function updateDrawNumbers() {
        console.log("Updating draw numbers with YOUR GENERATED RESULTS!");

        // Example: Replace these lines with your actual logic
        const newFirstPrize = "1234";
        const newSecondPrize = "5678";
        const newThirdPrize = "9012";
        const newSpecialResults = ["1111", "2222", "3333", "4444", "5555", "6666", "7777", "8888", "9999", "0000"];
        const newConsolationResults = ["1010", "2020", "3030", "4040", "5050", "6060", "7070", "8080", "9090", "0101"];
        const newJackpot1 = "RM 7,500,000.00";
        const newJackpot2 = "RM 250,000.00";
        const newDrawDate = "Thu 07-08-2025";
        const newDrawNo = "No.5951/25";

        // Step 1: Update metadata instantly
        document.querySelector('.jackpot-item:nth-child(1) .jackpot-amount').textContent = newJackpot1;
        document.querySelector('.jackpot-item:nth-child(2) .jackpot-amount').textContent = newJackpot2;
        document.querySelector('.draw-date').textContent = newDrawDate;
        document.querySelector('.draw-no').textContent = newDrawNo;
        
        setLanguage(document.getElementById('lang-select').value);

        // Step 2: Clear all number fields to placeholder just before the reveal
        resetNumbersToPlaceholder();

        // Step 3: Gather all the elements in the desired reveal order
        const allNumberElements = [
            document.querySelector('.prize-section.top-prizes .prize-row:nth-child(1) .prize-number'),
            document.querySelector('.prize-section.top-prizes .prize-row:nth-child(2) .prize-number'),
            document.querySelector('.prize-section.top-prizes .prize-row:nth-child(3) .prize-number'),
            ...document.querySelectorAll('.results-table.special-table tbody td'),
            ...document.querySelectorAll('.results-table.consolation-table tbody td')
        ];

        // Step 4: Combine the new values into one array in the same order
        const allNewValues = [
            newFirstPrize,
            newSecondPrize,
            newThirdPrize,
            ...newSpecialResults,
            ...newConsolationResults
        ];

        // Step 5: Start the slow reveal with a 5-second delay between each number
        const revealDelay = 5000; // 5000 milliseconds = 5 seconds
        slowReveal(allNumberElements, allNewValues, revealDelay);

        console.log("Draw numbers update process started!");
    }

    // --- Scheduling the Next Result ---
    function scheduleNextResult(hour, minute, second) {
        const now = new Date();
        const updateTime = new Date(now.getFullYear(), now.getMonth(), now.getDate(), hour, minute, second);

        if (updateTime.getTime() < now.getTime()) {
            updateTime.setDate(updateTime.getDate() + 1);
        }

        const timeToWait = updateTime.getTime() - now.getTime();
        console.log(`Next result update scheduled for: ${updateTime.toLocaleString()} (in ${timeToWait / 1000} seconds)`);

        setTimeout(() => {
            updateDrawNumbers();
            scheduleNextResult(hour, minute, second);
        }, timeToWait);
    }

    // --- NEW: TRANSLATION DICTIONARIES ---
    const translations = {
        en: {
            pageTitle: "DAHENG 4D - Best Lottery Best Prize !",
            brandName: "DAHENG 4D",
            navHome: "Home",
            navResults: "Results",
            navHowToPlay: "How to Play",
            navPrize: "Prize",
            navAbout: "About Us",
            navContact: "Contact",
            heroHeading: "Dream Big, Win Big!",
            heroSubheading: "Check the latest DA-HENG 4D results and play your lucky numbers today.",
            heroHowToPlay: "How to Play",
            heroLatestResults: "Latest Results",
            resultsHeading: "Official DAHENG 4D Results",
            resultsDescription: "Here are the latest official results for Thu 18-09-2025.",
            prizeLabel1: "1st Prize",
            prizeLabel2: "2nd Prize",
            prizeLabel3: "3rd Prize",
            tableSpecial: "Special",
            tableConsolation: "Consolation",
            jackpotLabel1: "4D jackpot 1",
            jackpotLabel2: "4D jackpot 2",
            viewPastResults: "View Past Results",
            nextDrawCountdown: "Next Draw Countdown",
            howToPlayHeading: "How to Play Daheng 4D",
            step1Heading: "1. Choose Your Numbers",
            step1Description: "Select any 4-digit number from 0000 to 9999. You can also choose 'Lucky Pick' for a randomly generated number.",
            step2Heading: "2. Select Your Bet Type",
            step2Description: "Choose 'Big' (permissible, ordinary, or sum) or 'Small' (permissible only) according to your preference.",
            step3Heading: "3. Place Your Bet",
            step3Description: "Decide on your bet amount for each chosen number and bet type. Minimum bet is RM 1.",
            step4Heading: "4. Check Results",
            step4Description: "Draws are held three times a week. Check back here for the latest results and see if you've won!",
            learnMore: "Learn More",
            newsHeading: "Latest News & Announcements",
            newsItem1Heading: "Exciting New Game Coming Soon!",
            newsItem1Date: "August 5, 2025",
            newsItem1Description: "Stay tuned for an announcement about a brand new lottery game with even bigger jackpots!",
            newsItem2Heading: "Daheng Community Outreach Program",
            newsItem2Date: "July 28, 2025",
            newsItem2Description: "We're proud to support local communities through our latest CSR initiatives. Find out more.",
            readMore: "Read More",
            viewAllNews: "View All News",
            aboutHeading: "About Daheng 4D",
            aboutParagraph1: "Da-Heng 4D is one of the leading lottery operators, committed to providing fair and transparent games. We are dedicated to responsible gaming and contribute significantly to social welfare through our charitable initiatives. Since our inception, we have been a part of millions of dreams and winners' stories.",
            aboutParagraph2: "Our commitment extends beyond just lottery games; we strive to make a positive impact on society, supporting various community projects and welfare organizations.",
            ourStory: "Our Story",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Dream Big, Win Bigger!",
            footerQuickLinks: "Quick Links",
            navHomeFooter: "Home",
            navResultsFooter: "Latest Results",
            navHowToPlayFooter: "How to Play",
            navNewsFooter: "News & Events",
            footerSupport: "Support",
            supportFAQ: "FAQ",
            supportContact: "Contact Us",
            supportGaming: "Responsible Gaming",
            supportPrivacy: "Privacy Policy",
            footerContactUs: "Contact Us",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malaysia",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 Daheng 4D. All Rights Reserved. For 18+ only. Play Responsibly.",
            disclaimer: "Disclaimer: This is a fictional website for demonstration purposes. Actual lottery results and information may vary."
        },
        ms: {
            pageTitle: "DAHENG 4D - Loteri Terbaik, Hadiah Terhebat!",
            brandName: "DAHENG 4D",
            navHome: "Laman Utama",
            navResults: "Keputusan",
            navHowToPlay: "Cara Bermain",
            navPrize: "Hadiah",
            navAbout: "Tentang Kami",
            navContact: "Hubungi Kami",
            heroHeading: "Impian Besar, Menang Besar!",
            heroSubheading: "Semak keputusan 4D DA-HENG terkini dan main nombor bertuah anda hari ini.",
            heroHowToPlay: "Cara Bermain",
            heroLatestResults: "Keputusan Terkini",
            resultsHeading: "Keputusan Rasmi DAHENG 4D",
            resultsDescription: "Berikut adalah keputusan rasmi terkini untuk Khamis 18-09-2025 .",
            prizeLabel1: "Hadiah Pertama",
            prizeLabel2: "Hadiah Kedua",
            prizeLabel3: "Hadiah Ketiga",
            tableSpecial: "Khas",
            tableConsolation: "Saguh hati",
            jackpotLabel1: "Jackpot 4D 1",
            jackpotLabel2: "Jackpot 4D 2",
            viewPastResults: "Lihat Keputusan Lalu",
            nextDrawCountdown: "Kiraan Detik Cabutan Seterusnya",
            howToPlayHeading: "Cara Bermain Daheng 4D",
            step1Heading: "1. Pilih Nombor Anda",
            step1Description: "Pilih mana-mana nombor 4 digit dari 0000 hingga 9999. Anda juga boleh memilih 'Pilihan Bertuah' untuk nombor yang dijana secara rawak.",
            step2Heading: "2. Pilih Jenis Pertaruhan Anda",
            step2Description: "Pilih 'Besar' (dibenarkan, biasa, atau jumlah) atau 'Kecil' (dibenarkan sahaja) mengikut pilihan anda.",
            step3Heading: "3. Letakkan Pertaruhan Anda",
            step3Description: "Tentukan jumlah pertaruhan anda untuk setiap nombor dan jenis pertaruhan yang dipilih. Pertaruhan minimum ialah RM 1.",
            step4Heading: "4. Semak Keputusan",
            step4Description: "Cabutan diadakan tiga kali seminggu. Semak semula di sini untuk keputusan terkini dan lihat jika anda telah menang!",
            learnMore: "Ketahui Lebih Lanjut",
            newsHeading: "Berita & Pengumuman Terkini",
            newsItem1Heading: "Permainan Baharu yang Menarik Akan Datang!",
            newsItem1Date: "5 Ogos 2025",
            newsItem1Description: "Nantikan pengumuman tentang permainan loteri baharu dengan jackpot yang lebih besar!",
            newsItem2Heading: "Program Jangkauan Komuniti Daheng",
            newsItem2Date: "28 Julai 2025",
            newsItem2Description: "Kami bangga menyokong komuniti tempatan melalui inisiatif CSR terbaru kami. Ketahui lebih lanjut.",
            readMore: "Baca Lebih Lanjut",
            viewAllNews: "Lihat Semua Berita",
            aboutHeading: "Mengenai Daheng 4D",
            aboutParagraph1: "Da-Heng 4D adalah salah satu pengendali loteri terkemuka, komited untuk menyediakan permainan yang adil dan telus. Kami berdedikasi untuk permainan yang bertanggungjawab dan menyumbang secara signifikan kepada kebajikan sosial melalui inisiatif amal kami. Sejak penubuhan kami, kami telah menjadi sebahagian daripada jutaan impian dan kisah pemenang.",
            aboutParagraph2: "Komitmen kami melangkaui sekadar permainan loteri; kami berusaha untuk membuat impak positif kepada masyarakat, menyokong pelbagai projek komuniti dan organisasi kebajikan.",
            ourStory: "Kisah Kami",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Impian Besar, Menang Lebih Besar!",
            footerQuickLinks: "Pautan Pantas",
            navHomeFooter: "Laman Utama",
            navResultsFooter: "Keputusan Terkini",
            navHowToPlayFooter: "Cara Bermain",
            navNewsFooter: "Berita & Acara",
            footerSupport: "Sokongan",
            supportFAQ: "Soalan Lazim",
            supportContact: "Hubungi Kami",
            supportGaming: "Permainan Bertanggungjawab",
            supportPrivacy: "Dasar Privasi",
            footerContactUs: "Hubungi Kami",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malaysia",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 Daheng 4D. Semua Hak Cipta Terpelihara. Untuk 18+ sahaja. Main dengan Bertanggungjawab.",
            disclaimer: "Penafian: Ini adalah laman web fiksyen untuk tujuan demonstrasi. Keputusan loteri sebenar dan maklumat mungkin berbeza."
        },
        zh: {
            pageTitle: "DAHENG 4D - 最好的彩票，最棒的奖品！",
            brandName: "DAHENG 4D",
            navHome: "主页",
            navResults: "开彩成绩",
            navHowToPlay: "如何玩",
            navPrize: "奖金",
            navAbout: "关于我们",
            navContact: "联系我们",
            heroHeading: "梦想越大，中奖越大！",
            heroSubheading: "查询最新的DA-HENG 4D开彩成绩，今天就玩你的幸运号码吧。",
            heroHowToPlay: "如何玩",
            heroLatestResults: "最新开彩",
            resultsHeading: "DAHENG 4D官方开彩成绩",
            resultsDescription: "以下是2025年9月18日星期四 的最新官方开彩成绩。",
            prizeLabel1: "头奖",
            prizeLabel2: "二奖",
            prizeLabel3: "三奖",
            tableSpecial: "特别奖",
            tableConsolation: "安慰奖",
            jackpotLabel1: "4D积宝 1",
            jackpotLabel2: "4D积宝 2",
            viewPastResults: "查看过往成绩",
            nextDrawCountdown: "下一次开彩倒计时",
            howToPlayHeading: "如何玩Daheng 4D",
            step1Heading: "1. 选择你的号码",
            step1Description: "选择任何一个0000到9999之间的4位数号码。您也可以选择'幸运选号'来随机生成号码。",
            step2Heading: "2. 选择你的下注类型",
            step2Description: "根据您的喜好选择“大”（可互换、普通或总和）或“小”（仅限可互换）。",
            step3Heading: "3. 下注",
            step3Description: "决定您为每个选定号码和下注类型下注的金额。最低下注金额为RM 1。",
            step4Heading: "4. 查看成绩",
            step4Description: "每周举行三次开彩。请回到这里查看最新成绩，看看您是否中奖！",
            learnMore: "了解更多",
            newsHeading: "最新消息与公告",
            newsItem1Heading: "激动人心的新游戏即将推出！",
            newsItem1Date: "2025年8月5日",
            newsItem1Description: "敬请期待关于一款全新彩票游戏的公告，奖金将更加丰厚！",
            newsItem2Heading: "大恒社区外展计划",
            newsItem2Date: "2025年7月28日",
            newsItem2Description: "我们很自豪通过最新的企业社会责任（CSR）举措来支持当地社区。了解更多信息。",
            readMore: "阅读更多",
            viewAllNews: "查看所有新闻",
            aboutHeading: "关于Daheng 4D",
            aboutParagraph1: "Da-Heng 4D是领先的彩票运营商之一，致力于提供公平透明的游戏。我们致力于负责任的博彩，并通过我们的慈善活动为社会福利做出重大贡献。自成立以来，我们一直是数百万个梦想和中奖故事的一部分。",
            aboutParagraph2: "我们的承诺不仅仅局限于彩票游戏；我们努力对社会产生积极影响，支持各种社区项目和福利组织。",
            ourStory: "我们的故事",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "梦想越大，中奖越大！",
            footerQuickLinks: "快速链接",
            navHomeFooter: "主页",
            navResultsFooter: "最新开彩",
            navHowToPlayFooter: "如何玩",
            navNewsFooter: "新闻与活动",
            footerSupport: "支持",
            supportFAQ: "常见问题",
            supportContact: "联系我们",
            supportGaming: "负责任博彩",
            supportPrivacy: "隐私政策",
            footerContactUs: "联系我们",
            contactAddress: "彩票巷，吉隆坡，马来西亚",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. All Rights Reserved. For 18+ only. Play Responsibly.",
            disclaimer: "免责声明：这是一个用于演示目的的虚构网站。实际的彩票结果和信息可能会有所不同。"
        },
        fzh: {
            pageTitle: "DAHENG 4D - 最好的彩票，最棒的獎品！",
            brandName: "DAHENG 4D",
            navHome: "主頁",
            navResults: "開彩成績",
            navHowToPlay: "如何玩",
            navPrize: "獎金",
            navAbout: "關於我們",
            navContact: "聯繫我們",
            heroHeading: "夢想越大，中獎越大！",
            heroSubheading: "查詢最近的DA-HENG 4D開採成績，今天就玩你的幸運號碼吧。",
            heroHowToPlay: "如何玩",
            heroLatestResults: "最新開彩",
            resultsHeading: "DAHENG 4D官方开彩成績",
            resultsDescription: "以下是2025年9月18日星期四 的最新官方开彩成绩。",
            prizeLabel1: "头獎",
            prizeLabel2: "二獎",
            prizeLabel3: "三獎",
            tableSpecial: "特别獎",
            tableConsolation: "安慰獎",
            jackpotLabel1: "4D積寶 1",
            jackpotLabel2: "4D積寶 2",
            viewPastResults: "查看過往成績",
            nextDrawCountdown: "下一次开彩倒計時",
            howToPlayHeading: "如何玩Daheng 4D",
            step1Heading: "1. 選擇你的號碼",
            step1Description: "選擇任何一个0000到9999之间的4位數號碼。您也可以選擇'幸運選號'来隨機生成號碼。",
            step2Heading: "2. 選擇你的下注類型",
            step2Description: "根据您的喜好选择“大”（可互换、普通或总和）或“小”（仅限可互换）。",
            step3Heading: "3. 下注",
            step3Description: "决定您为每个选定号码和下注类型下注的金额。最低下注金额为RM 1。",
            step4Heading: "4. 查看成绩",
            step4Description: "每周举行三次开彩。请回到这里查看最新成绩，看看您是否中奖！",
            learnMore: "了解更多",
            newsHeading: "最新消息与公告",
            newsItem1Heading: "激动人心的新游戏即将推出！",
            newsItem1Date: "2025年8月5日",
            newsItem1Description: "敬请期待关于一款全新彩票游戏的公告，奖金将更加丰厚！",
            newsItem2Heading: "大恒社区外展计划",
            newsItem2Date: "2025年7月28日",
            newsItem2Description: "我们很自豪通过最新的企业社会责任（CSR）举措来支持当地社区。了解更多信息。",
            readMore: "阅读更多",
            viewAllNews: "查看所有新闻",
            aboutHeading: "关于Daheng 4D",
            aboutParagraph1: "Da-Heng 4D是领先的彩票运营商之一，致力于提供公平透明的游戏。我们致力于负责任的博彩，并通过我们的慈善活动为社会福利做出重大贡献。自成立以来，我们一直是数百万个梦想和中奖故事的一部分。",
            aboutParagraph2: "我们的承诺不仅仅局限于彩票游戏；我们努力对社会产生积极影响，支持各种社区项目和福利组织。",
            ourStory: "我们的故事",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "梦想越大，中奖越大！",
            footerQuickLinks: "快速链接",
            navHomeFooter: "主页",
            navResultsFooter: "最新开彩",
            navHowToPlayFooter: "如何玩",
            navNewsFooter: "新闻与活动",
            footerSupport: "支持",
            supportFAQ: "常见问题",
            supportContact: "联系我们",
            supportGaming: "负责任博彩",
            supportPrivacy: "隐私政策",
            footerContactUs: "联系我们",
            contactAddress: "彩票巷，吉隆坡，马来西亚",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. All Rights Reserved. For 18+ only. Play Responsibly.",
            disclaimer: "免责声明：这是一个用于演示目的的虚构网站。实际的彩票结果和信息可能会有所不同。"
        },
        th: {
            pageTitle: "DAHENG 4D - หวยที่ดีที่สุด รางวัลที่ดีที่สุด!",
            brandName: "DAHENG 4D",
            navHome: "หน้าแรก",
            navResults: "ผลลัพธ์",
            navHowToPlay: "วิธีเล่น",
            navPrize: "รางวัล",
            navAbout: "เกี่ยวกับเรา",
            navContact: "ติดต่อ",
            heroHeading: "ฝันให้ใหญ่ ชนะให้ใหญ่!",
            heroSubheading: "ตรวจสอบผล 4D DA-HENG ล่าสุดและเล่นเลขนำโชคของคุณวันนี้",
            heroHowToPlay: "วิธีเล่น",
            heroLatestResults: "ผลลัพธ์ล่าสุด",
            resultsHeading: "ผล 4D DAHENG อย่างเป็นทางการ",
            resultsDescription: "นี่คือผลอย่างเป็นทางการล่าสุดสำหรับวันพฤหัสบดีที่ 18-09-2025 ",
            prizeLabel1: "รางวัลที่ 1",
            prizeLabel2: "รางวัลที่ 2",
            prizeLabel3: "รางวัลที่ 3",
            tableSpecial: "รางวัลพิเศษ",
            tableConsolation: "รางวัลปลอบใจ",
            jackpotLabel1: "แจ็คพอต 4D 1",
            jackpotLabel2: "แจ็คพอต 4D 2",
            viewPastResults: "ดูผลลัพธ์ย้อนหลัง",
            nextDrawCountdown: "นับถอยหลังงวดถัดไป",
            howToPlayHeading: "วิธีเล่น Daheng 4D",
            step1Heading: "1. เลือกตัวเลขของคุณ",
            step1Description: "เลือกตัวเลข 4 หลักใดก็ได้ตั้งแต่ 0000 ถึง 9999. คุณยังสามารถเลือก 'Lucky Pick' สำหรับตัวเลขที่สร้างขึ้นแบบสุ่ม",
            step2Heading: "2. เลือกประเภทการเดิมพัน",
            step2Description: "เลือก 'ใหญ่' (แบบอนุญาต, แบบธรรมดา หรือแบบรวม) หรือ 'เล็ก' (แบบอนุญาตเท่านั้น) ตามความต้องการของคุณ",
            step3Heading: "3. วางเดิมพันของคุณ",
            step3Description: "ตัดสินใจจำนวนเงินเดิมพันของคุณสำหรับแต่ละตัวเลขและประเภทการเดิมพันที่เลือก เดิมพันขั้นต่ำคือ RM 1.",
            step4Heading: "4. ตรวจสอบผลลัพธ์",
            step4Description: "การออกรางวัลจัดขึ้นสัปดาห์ละสามครั้ง กลับมาตรวจสอบที่นี่สำหรับผลลัพธ์ล่าสุดและดูว่าคุณชนะหรือไม่!",
            learnMore: "เรียนรู้เพิ่มเติม",
            newsHeading: "ข่าวสารและประกาศล่าสุด",
            newsItem1Heading: "เกมใหม่ที่น่าตื่นเต้นกำลังจะมาเร็วๆ นี้!",
            newsItem1Date: "5 สิงหาคม 2568",
            newsItem1Description: "คอยติดตามประกาศเกี่ยวกับเกมลอตเตอรีใหม่ล่าสุดพร้อมแจ็คพอตที่ใหญ่กว่าเดิม!",
            newsItem2Heading: "โครงการช่วยเหลือชุมชน Daheng",
            newsItem2Date: "28 กรกฎาคม 2568",
            newsItem2Description: "เราภูมิใจที่ได้สนับสนุนชุมชนท้องถิ่นผ่านโครงการ CSR ล่าสุดของเรา ค้นหาข้อมูลเพิ่มเติม.",
            readMore: "อ่านเพิ่มเติม",
            viewAllNews: "ดูข่าวทั้งหมด",
            aboutHeading: "เกี่ยวกับ Daheng 4D",
            aboutParagraph1: "Da-Heng 4D เป็นหนึ่งในผู้ให้บริการลอตเตอรีชั้นนำ มุ่งมั่นที่จะให้บริการเกมที่ยุติธรรมและโปร่งใส เราทุ่มเทให้กับการเล่นเกมอย่างมีความรับผิดชอบและมีส่วนร่วมอย่างมากในสวัสดิการสังคมผ่านโครงการการกุศลของเรา นับตั้งแต่ก่อตั้ง เราเป็นส่วนหนึ่งของความฝันและเรื่องราวของผู้ชนะหลายล้านคน",
            aboutParagraph2: "ความมุ่งมั่นของเราขยายไปไกลกว่าแค่เกมลอตเตอรี เรามุ่งมั่นที่จะสร้างผลกระทบเชิงบวกต่อสังคม สนับสนุนโครงการชุมชนและองค์กรสวัสดิการต่างๆ",
            ourStory: "เรื่องราวของเรา",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "ฝันให้ใหญ่ ชนะให้ใหญ่กว่า!",
            footerQuickLinks: "ลิงค์ด่วน",
            navHomeFooter: "หน้าแรก",
            navResultsFooter: "ผลลัพธ์ล่าสุด",
            navHowToPlayFooter: "วิธีเล่น",
            navNewsFooter: "ข่าวสารและกิจกรรม",
            footerSupport: "สนับสนุน",
            supportFAQ: "คำถามที่พบบ่อย",
            supportContact: "ติดต่อเรา",
            supportGaming: "การเล่นเกมอย่างรับผิดชอบ",
            supportPrivacy: "นโยบายความเป็นส่วนตัว",
            footerContactUs: "ติดต่อเรา",
            contactAddress: "ซอยลอตเตอรี่, กัวลาลัมเปอร์, มาเลเซีย",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. สงวนลิขสิทธิ์. สำหรับผู้ที่มีอายุ 18+ เท่านั้น. เล่นอย่างมีความรับผิดชอบ.",
            disclaimer: "ข้อสงวนสิทธิ์: นี่คือเว็บไซต์สมมติเพื่อวัตถุประสงค์ในการสาธิต ผลลัพธ์ลอตเตอรีจริงและข้อมูลอาจแตกต่างกันไป."
        },
        fil: {
            pageTitle: "DAHENG 4D - Pinakamahusay na Lottery Pinakamahusay na Premyo!",
            brandName: "DAHENG 4D",
            navHome: "Home",
            navResults: "Mga Resulta",
            navHowToPlay: "Paano Maglaro",
            navPrize: "Premyo",
            navAbout: "Tungkol sa Amin",
            navContact: "Kontakin Kami",
            heroHeading: "Mangangarap Nang Malaki, Manalo Nang Malaki!",
            heroSubheading: "Suriin ang pinakabagong mga resulta ng DA-HENG 4D at laruin ang iyong mga masuwerteng numero ngayon.",
            heroHowToPlay: "Paano Maglaro",
            heroLatestResults: "Pinakabagong Mga Resulta",
            resultsHeading: "Mga Opisyal na Resulta ng DAHENG 4D",
            resultsDescription: "Narito ang pinakabagong mga opisyal na resulta para sa Huwebes 18-09-2025 .",
            prizeLabel1: "Unang Premyo",
            prizeLabel2: "Pangalawang Premyo",
            prizeLabel3: "Ikatlong Premyo",
            tableSpecial: "Espesyal",
            tableConsolation: "Consolation",
            jackpotLabel1: "4D Jackpot 1",
            jackpotLabel2: "4D Jackpot 2",
            viewPastResults: "Tingnan ang mga Nakaraang Resulta",
            nextDrawCountdown: "Countdown sa Susunod na Draw",
            howToPlayHeading: "Paano Maglaro ng Daheng 4D",
            step1Heading: "1. Piliin ang Iyong mga Numero",
            step1Description: "Pumili ng anumang 4-digit na numero mula 0000 hanggang 9999. Maaari ka ring pumili ng 'Lucky Pick' para sa isang random na nabuong numero.",
            step2Heading: "2. Piliin ang Uri ng Iyong Pusta",
            step2Description: "Pumili ng 'Big' (permissible, ordinary, o sum) o 'Small' (permissible lang) ayon sa iyong kagustuhan.",
            step3Heading: "3. Ilagay ang Iyong Pusta",
            step3Description: "Magpasya sa halaga ng iyong pusta para sa bawat napiling numero at uri ng pusta. Ang minimum na pusta ay RM 1.",
            step4Heading: "4. Suriin ang mga Resulta",
            step4Description: "Ang mga draw ay ginaganap tatlong beses sa isang linggo. Balikan dito para sa pinakabagong mga resulta at tingnan kung ikaw ay nanalo!",
            learnMore: "Matuto Nang Higit Pa",
            newsHeading: "Pinakabagong Balita at Mga Anunsyo",
            newsItem1Heading: "Paparating Na Ang Isang Bagong Larong Nakakatuwa!",
            newsItem1Date: "Agosto 5, 2025",
            newsItem1Description: "Manatiling nakatutok para sa isang anunsyo tungkol sa isang bagong laro ng lottery na may mas malaking jackpots!",
            newsItem2Heading: "Programa ng Daheng Community Outreach",
            newsItem2Date: "Hulyo 28, 2025",
            newsItem2Description: "Ipinagmamalaki naming suportahan ang mga lokal na komunidad sa pamamagitan ng aming pinakabagong mga inisyatibo sa CSR. Alamin ang higit pa.",
            readMore: "Magbasa Nang Higit Pa",
            viewAllNews: "Tingnan ang Lahat ng Balita",
            aboutHeading: "Tungkol sa Daheng 4D",
            aboutParagraph1: "Ang Da-Heng 4D ay isa sa mga nangungunang operator ng lottery, na nakatuon sa pagbibigay ng patas at transparent na mga laro. Kami ay nakatuon sa responsableng paglalaro at nag-aambag nang malaki sa kapakanang panlipunan sa pamamagitan ng aming mga inisyatibo sa kawanggawa. Mula nang magsimula kami, naging bahagi kami ng milyun-milyong pangarap at mga kuwento ng mga nanalo.",
            aboutParagraph2: "Ang aming pangako ay higit pa sa mga laro ng lottery; nagsusumikap kaming gumawa ng positibong epekto sa lipunan, sumusuporta sa iba't ibang mga proyekto ng komunidad at mga organisasyon ng kapakanan.",
            ourStory: "Ang Aming Kuwento",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Mangangarap Nang Malaki, Manalo Nang Malaki!",
            footerQuickLinks: "Mabilis na Mga Link",
            navHomeFooter: "Home",
            navResultsFooter: "Pinakabagong Mga Resulta",
            navHowToPlayFooter: "Paano Maglaro",
            navNewsFooter: "Balita at Kaganapan",
            footerSupport: "Suporta",
            supportFAQ: "FAQ",
            supportContact: "Kontakin Kami",
            supportGaming: "Responsableng Paglalaro",
            supportPrivacy: "Patakaran sa Privacy",
            footerContactUs: "Kontakin Kami",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malaysia",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. Lahat ng Karapatan ay Nakalaan. Para sa 18+ lang. Maglaro nang Responsable.",
            disclaimer: "Disclaimer: Ito ay isang kathang-isip na website para sa mga layunin ng demonstrasyon. Maaaring mag-iba ang aktwal na mga resulta ng lottery at impormasyon."
        },
        id: {
            pageTitle: "DAHENG 4D - Lotere Terbaik Hadiah Terbaik!",
            brandName: "DAHENG 4D",
            navHome: "Beranda",
            navResults: "Hasil",
            navHowToPlay: "Cara Bermain",
            navPrize: "Hadiah",
            navAbout: "Tentang Kami",
            navContact: "Kontak",
            heroHeading: "Bermimpi Besar, Menang Besar!",
            heroSubheading: "Periksa hasil DA-HENG 4D terbaru dan mainkan nomor keberuntungan Anda hari ini.",
            heroHowToPlay: "Cara Bermain",
            heroLatestResults: "Hasil Terbaru",
            resultsHeading: "Hasil Resmi DAHENG 4D",
            resultsDescription: "Berikut adalah hasil resmi terbaru untuk Kamis 18-09-2025 .",
            prizeLabel1: "Hadiah Pertama",
            prizeLabel2: "Hadiah Kedua",
            prizeLabel3: "Hadiah Ketiga",
            tableSpecial: "Khusus",
            tableConsolation: "Hiburan",
            jackpotLabel1: "Jackpot 4D 1",
            jackpotLabel2: "Jackpot 4D 2",
            viewPastResults: "Lihat Hasil Sebelumnya",
            nextDrawCountdown: "Hitung Mundur Undian Berikutnya",
            howToPlayHeading: "Cara Bermain Daheng 4D",
            step1Heading: "1. Pilih Nomor Anda",
            step1Description: "Pilih nomor 4 digit dari 0000 hingga 9999. Anda juga bisa memilih 'Lucky Pick' untuk nomor yang dibuat secara acak.",
            step2Heading: "2. Pilih Jenis Taruhan Anda",
            step2Description: "Pilih 'Besar' (diizinkan, biasa, atau jumlah) atau 'Kecil' (hanya diizinkan) sesuai dengan preferensi Anda.",
            step3Heading: "3. Pasang Taruhan Anda",
            step3Description: "Tentukan jumlah taruhan Anda untuk setiap nomor dan jenis taruhan yang dipilih. Taruhan minimum adalah RM 1.",
            step4Heading: "4. Periksa Hasil",
            step4Description: "Undian diadakan tiga kali seminggu. Kembali ke sini untuk hasil terbaru dan lihat apakah Anda menang!",
            learnMore: "Pelajari Lebih Lanjut",
            newsHeading: "Berita & Pengumuman Terbaru",
            newsItem1Heading: "Game Baru yang Menarik Segera Hadir!",
            newsItem1Date: "5 Agustus 2025",
            newsItem1Description: "Nantikan pengumuman tentang game lotere baru dengan jackpot yang lebih besar!",
            newsItem2Heading: "Program Jangkauan Komunitas Daheng",
            newsItem2Date: "28 Juli 2025",
            newsItem2Description: "Kami bangga mendukung komunitas lokal melalui inisiatif CSR terbaru kami. Cari tahu lebih lanjut.",
            readMore: "Baca Selengkapnya",
            viewAllNews: "Lihat Semua Berita",
            aboutHeading: "Tentang Daheng 4D",
            aboutParagraph1: "Da-Heng 4D adalah salah satu operator lotere terkemuka, berkomitmen untuk menyediakan permainan yang adil dan transparan. Kami berdedikasi untuk permainan yang bertanggung jawab dan berkontribusi secara signifikan pada kesejahteraan sosial melalui inisiatif amal kami. Sejak awal, kami telah menjadi bagian dari jutaan mimpi dan cerita pemenang.",
            aboutParagraph2: "Komitmen kami melampaui sekadar permainan lotere; kami berusaha untuk membuat dampak positif pada masyarakat, mendukung berbagai proyek komunitas dan organisasi kesejahteraan.",
            ourStory: "Kisah Kami",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Bermimpi Besar, Menang Lebih Besar!",
            footerQuickLinks: "Tautan Cepat",
            navHomeFooter: "Beranda",
            navResultsFooter: "Hasil Terbaru",
            navHowToPlayFooter: "Cara Bermain",
            navNewsFooter: "Berita & Acara",
            footerSupport: "Dukungan",
            supportFAQ: "FAQ",
            supportContact: "Hubungi Kami",
            supportGaming: "Permainan Bertanggung Jawab",
            supportPrivacy: "Kebijakan Privasi",
            footerContactUs: "Hubungi Kami",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malaysia",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. Hak Cipta Dilindungi. Hanya untuk 18+. Bermainlah dengan Bertanggung Jawab.",
            disclaimer: "Penafian: Ini adalah situs web fiktif untuk tujuan demonstrasi. Hasil lotere dan informasi aktual dapat bervariasi."
        },
        ta: {
            pageTitle: "DAHENG 4D - சிறந்த லாட்டரி சிறந்த பரிசு!",
            brandName: "DAHENG 4D",
            navHome: "முகப்பு",
            navResults: "முடிவுகள்",
            navHowToPlay: "எப்படி விளையாடுவது",
            navPrize: "பரிசு",
            navAbout: "எங்களைப் பற்றி",
            navContact: "தொடர்பு கொள்ளவும்",
            heroHeading: "பெரிய கனவு காணுங்கள், பெரிய அளவில் வெல்லுங்கள்!",
            heroSubheading: "சமீபத்திய DA-HENG 4D முடிவுகளைச் சரிபார்த்து, உங்கள் அதிர்ஷ்ட எண்களை இன்றே விளையாடுங்கள்.",
            heroHowToPlay: "எப்படி விளையாடுவது",
            heroLatestResults: "சமீபத்திய முடிவுகள்",
            resultsHeading: "அதிகாரபூர்வமான DAHENG 4D முடிவுகள்",
            resultsDescription: "வியாழன் 18-09-2025 க்கான சமீபத்திய அதிகாரப்பூர்வ முடிவுகள் இங்கே உள்ளன.",
            prizeLabel1: "1வது பரிசு",
            prizeLabel2: "2வது பரிசு",
            prizeLabel3: "3வது பரிசு",
            tableSpecial: "சிறப்பு",
            tableConsolation: "ஆறுதல்",
            jackpotLabel1: "4D ஜாக்பாட் 1",
            jackpotLabel2: "4D ஜாக்பாட் 2",
            viewPastResults: "கடந்த முடிவுகளைப் பார்க்கவும்",
            nextDrawCountdown: "அடுத்த குலுக்கல் கவுண்டவுன்",
            howToPlayHeading: "Daheng 4D விளையாடுவது எப்படி",
            step1Heading: "1. உங்கள் எண்களைத் தேர்ந்தெடுக்கவும்",
            step1Description: "0000 முதல் 9999 வரையிலான எந்த 4 இலக்க எண்ணையும் தேர்ந்தெடுக்கவும். தோராயமாக உருவாக்கப்பட்ட எண்ணுக்கு 'லக்கி பிக்' என்பதையும் நீங்கள் தேர்ந்தெடுக்கலாம்.",
            step2Heading: "2. உங்கள் பந்தய வகையைத் தேர்ந்தெடுக்கவும்",
            step2Description: "உங்கள் விருப்பப்படி 'பெரிய' (அனுமதிக்கப்பட்ட, சாதாரண அல்லது கூட்டு) அல்லது 'சிறிய' (அனுமதிக்கப்பட்ட மட்டும்) என்பதைத் தேர்ந்தெடுக்கவும்.",
            step3Heading: "3. உங்கள் பந்தயத்தை வைக்கவும்",
            step3Description: "தேர்ந்தெடுக்கப்பட்ட ஒவ்வொரு எண்ணுக்கும் மற்றும் பந்தய வகைக்கும் உங்கள் பந்தயத் தொகையை முடிவு செய்யுங்கள். குறைந்தபட்ச பந்தயம் RM 1.",
            step4Heading: "4. முடிவுகளைச் சரிபார்க்கவும்",
            step4Description: "வாரத்தில் மூன்று முறை குலுக்கல்கள் நடத்தப்படுகின்றன. சமீபத்திய முடிவுகளுக்காக இங்கு வந்து நீங்கள் வென்றீர்களா என்பதைப் பாருங்கள்!",
            learnMore: "மேலும் அறிய",
            newsHeading: "சமீபத்திய செய்திகள் & அறிவிப்புகள்",
            newsItem1Heading: "அற்புதமான புதிய விளையாட்டு விரைவில் வருகிறது!",
            newsItem1Date: "ஆகஸ்ட் 5, 2025",
            newsItem1Description: "மிகப்பெரிய ஜாக்பாட்களுடன் புதிய லாட்டரி விளையாட்டு பற்றிய அறிவிப்புக்காக காத்திருங்கள்!",
            newsItem2Heading: "Daheng சமூக outreach திட்டம்",
            newsItem2Date: "ஜூலை 28, 2025",
            newsItem2Description: "எங்கள் சமீபத்திய CSR முன்முயற்சிகள் மூலம் உள்ளூர் சமூகங்களுக்கு ஆதரவளிப்பதில் நாங்கள் பெருமைப்படுகிறோம். மேலும் அறியவும்.",
            readMore: "மேலும் படிக்க",
            viewAllNews: "அனைத்து செய்திகளையும் காண்க",
            aboutHeading: "Daheng 4D பற்றி",
            aboutParagraph1: "Da-Heng 4D என்பது முன்னணி லாட்டரி ஆபரேட்டர்களில் ஒன்றாகும், இது நியாயமான மற்றும் வெளிப்படையான விளையாட்டுகளை வழங்குவதில் உறுதிபூண்டுள்ளது. நாங்கள் பொறுப்பான விளையாட்டிற்கு அர்ப்பணித்துள்ளோம் மற்றும் எங்கள் தொண்டு முயற்சிகள் மூலம் சமூக நலனுக்கு கணிசமாக பங்களிக்கிறோம். எங்கள் தொடக்கத்திலிருந்தே, நாங்கள் மில்லியன் கணக்கான கனவுகள் மற்றும் வெற்றியாளர்களின் கதைகளின் ஒரு பகுதியாக இருக்கிறோம்.",
            aboutParagraph2: "எங்கள் அர்ப்பணிப்பு லாட்டரி விளையாட்டுகளுக்கு அப்பாற்பட்டது; பல்வேறு சமூகத் திட்டங்கள் மற்றும் நலன்புரி நிறுவனங்களை ஆதரிப்பதன் மூலம் சமூகத்தில் நேர்மறையான தாக்கத்தை ஏற்படுத்த நாங்கள் பாடுபடுகிறோம்.",
            ourStory: "எங்கள் கதை",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "பெரிய கனவு காணுங்கள், பெரிய அளவில் வெல்லுங்கள்!",
            footerQuickLinks: "விரைவு இணைப்புகள்",
            navHomeFooter: "முகப்பு",
            navResultsFooter: "சமீபத்திய முடிவுகள்",
            navHowToPlayFooter: "எப்படி விளையாடுவது",
            navNewsFooter: "செய்திகள் & நிகழ்வுகள்",
            footerSupport: "ஆதரவு",
            supportFAQ: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
            supportContact: "எங்களை தொடர்பு கொள்ளவும்",
            supportGaming: "பொறுப்பான விளையாட்டு",
            supportPrivacy: "தனியுரிமைக் கொள்கை",
            footerContactUs: "எங்களை தொடர்பு கொள்ளவும்",
            contactAddress: "லாட்டரி லேன், கோலாலம்பூர், மலேசியா",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. 18+க்கு மட்டும். பொறுப்புடன் விளையாடுங்கள்.",
            disclaimer: "துறப்பு: இது விளக்க நோக்கங்களுக்காக ஒரு கற்பனையான இணையதளம். உண்மையான லாட்டரி முடிவுகள் மற்றும் தகவல்கள் மாறுபடலாம்."
        },
        hi: {
            pageTitle: "DAHENG 4D - सबसे अच्छी लॉटरी सबसे अच्छा इनाम!",
            brandName: "DAHENG 4D",
            navHome: "होम",
            navResults: "परिणाम",
            navHowToPlay: "कैसे खेलें",
            navPrize: "इनाम",
            navAbout: "हमारे बारे में",
            navContact: "संपर्क",
            heroHeading: "बड़ा सपना देखें, बड़ा जीतें!",
            heroSubheading: "नवीनतम DA-HENG 4D परिणाम देखें और आज ही अपने भाग्यशाली नंबर खेलें।",
            heroHowToPlay: "कैसे खेलें",
            heroLatestResults: "नवीनतम परिणाम",
            resultsHeading: "आधिकारिक DAHENG 4D परिणाम",
            resultsDescription: "गुरुवार 18-09-2025  के नवीनतम आधिकारिक परिणाम यहाँ दिए गए हैं।",
            prizeLabel1: "पहला इनाम",
            prizeLabel2: "दूसरा इनाम",
            prizeLabel3: "तीसरा इनाम",
            tableSpecial: "विशेष",
            tableConsolation: "सांत्वना",
            jackpotLabel1: "4D जैकपॉट 1",
            jackpotLabel2: "4D जैकपॉट 2",
            viewPastResults: "पिछले परिणाम देखें",
            nextDrawCountdown: "अगला ड्रॉ उलटी गिनती",
            howToPlayHeading: "Daheng 4D कैसे खेलें",
            step1Heading: "1. अपने नंबर चुनें",
            step1Description: "0000 से 9999 तक कोई भी 4 अंकों का नंबर चुनें। आप यादृच्छिक रूप से उत्पन्न नंबर के लिए 'लकी पिक' भी चुन सकते हैं।",
            step2Heading: "2. अपनी शर्त का प्रकार चुनें",
            step2Description: "अपनी पसंद के अनुसार 'बड़ा' (अनुमेय, साधारण, या योग) या 'छोटा' (केवल अनुमेय) चुनें।",
            step3Heading: "3. अपनी शर्त लगाएं",
            step3Description: "प्रत्येक चुने हुए नंबर और शर्त के प्रकार के लिए अपनी शर्त की राशि तय करें। न्यूनतम शर्त RM 1 है।",
            step4Heading: "4. परिणाम देखें",
            step4Description: "ड्रॉ सप्ताह में तीन बार आयोजित किए जाते हैं। नवीनतम परिणामों के लिए यहाँ वापस जाएँ और देखें कि क्या आप जीते हैं!",
            learnMore: "और जानें",
            newsHeading: "नवीनतम समाचार और घोषणाएं",
            newsItem1Heading: "जल्द ही आ रहा है एक रोमांचक नया खेल!",
            newsItem1Date: "5 अगस्त, 2025",
            newsItem1Description: "और भी बड़े जैकपॉट के साथ एक बिल्कुल नए लॉटरी खेल के बारे में घोषणा के लिए बने रहें!",
            newsItem2Heading: "दाहेंग सामुदायिक आउटरीच कार्यक्रम",
            newsItem2Date: "28 जुलाई, 2025",
            newsItem2Description: "हम अपनी नवीनतम सीएसआर पहल के माध्यम से स्थानीय समुदायों का समर्थन करने में गर्व महसूस करते हैं। और जानें।",
            readMore: "और पढ़ें",
            viewAllNews: "सभी समाचार देखें",
            aboutHeading: "दाहेंग 4D के बारे में",
            aboutParagraph1: "दाहेंग 4D अग्रणी लॉटरी ऑपरेटरों में से एक है, जो निष्पक्ष और पारदर्शी खेल प्रदान करने के लिए प्रतिबद्ध है। हम जिम्मेदार गेमिंग के लिए समर्पित हैं और अपनी धर्मार्थ पहलों के माध्यम से सामाजिक कल्याण में महत्वपूर्ण योगदान करते हैं। हमारी स्थापना के बाद से, हम लाखों सपनों और विजेताओं की कहानियों का हिस्सा रहे हैं।",
            aboutParagraph2: "हमारी प्रतिबद्धता केवल लॉटरी खेलों से परे है; हम समाज पर सकारात्मक प्रभाव डालने, विभिन्न सामुदायिक परियोजनाओं और कल्याणकारी संगठनों का समर्थन करने का प्रयास करते हैं।",
            ourStory: "हमारी कहानी",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "बड़ा सपना देखें, और भी बड़ा जीतें!",
            footerQuickLinks: "त्वरित लिंक",
            navHomeFooter: "होम",
            navResultsFooter: "नवीनतम परिणाम",
            navHowToPlayFooter: "कैसे खेलें",
            navNewsFooter: "समाचार और घटनाक्रम",
            footerSupport: "समर्थन",
            supportFAQ: "अक्सर पूछे जाने वाले प्रश्न",
            supportContact: "हमसे संपर्क करें",
            supportGaming: "जिम्मेदार गेमिंग",
            supportPrivacy: "गोपनीयता नीति",
            footerContactUs: "हमसे संपर्क करें",
            contactAddress: "लॉटरी लेन, कुआलालंपुर, मलेशिया",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. सभी अधिकार सुरक्षित। केवल 18+ के लिए। जिम्मेदारी से खेलें।",
            disclaimer: "अस्वीकरण: यह प्रदर्शन उद्देश्यों के लिए एक काल्पनिक वेबसाइट है। वास्तविक लॉटरी परिणाम और जानकारी भिन्न हो सकती है।"
        },
        de: {
            pageTitle: "DAHENG 4D - Beste Lotterie, beste Preise!",
            brandName: "DAHENG 4D",
            navHome: "Startseite",
            navResults: "Ergebnisse",
            navHowToPlay: "Anleitung",
            navPrize: "Preise",
            navAbout: "Über Uns",
            navContact: "Kontakt",
            heroHeading: "Träume groß, gewinne groß!",
            heroSubheading: "Prüfe die neuesten DA-HENG 4D Ergebnisse und spiele heute deine Glückszahlen.",
            heroHowToPlay: "Anleitung",
            heroLatestResults: "Neueste Ergebnisse",
            resultsHeading: "Offizielle DAHENG 4D Ergebnisse",
            resultsDescription: "Hier sind die neuesten offiziellen Ergebnisse für Donnerstag, den 18.09.2025 .",
            prizeLabel1: "1. Preis",
            prizeLabel2: "2. Preis",
            prizeLabel3: "3. Preis",
            tableSpecial: "Spezial",
            tableConsolation: "Trostpreis",
            jackpotLabel1: "4D Jackpot 1",
            jackpotLabel2: "4D Jackpot 2",
            viewPastResults: "Vergangene Ergebnisse ansehen",
            nextDrawCountdown: "Nächster Ziehungs-Countdown",
            howToPlayHeading: "So spielt man Daheng 4D",
            step1Heading: "1. Wähle deine Zahlen",
            step1Description: "Wähle eine beliebige 4-stellige Zahl von 0000 bis 9999. Du kannst auch 'Lucky Pick' für eine zufällig generierte Zahl wählen.",
            step2Heading: "2. Wähle deine Wettart",
            step2Description: "Wähle je nach Vorliebe 'Groß' (zulässig, gewöhnlich oder Summe) oder 'Klein' (nur zulässig).",
            step3Heading: "3. Platziere deine Wette",
            step3Description: "Entscheide dich für deinen Wetteinsatz für jede gewählte Zahl und Wettart. Der Mindesteinsatz beträgt RM 1.",
            step4Heading: "4. Prüfe die Ergebnisse",
            step4Description: "Die Ziehungen finden dreimal pro Woche statt. Schau hier wieder vorbei, um die neuesten Ergebnisse zu sehen und zu prüfen, ob du gewonnen hast!",
            learnMore: "Mehr erfahren",
            newsHeading: "Neueste Nachrichten & Ankündigungen",
            newsItem1Heading: "Spannendes neues Spiel kommt bald!",
            newsItem1Date: "5. August 2025",
            newsItem1Description: "Bleib dran für eine Ankündigung über ein brandneues Lotteriespiel mit noch größeren Jackpots!",
            newsItem2Heading: "Daheng Gemeinschafts-Outreach-Programm",
            newsItem2Date: "28. Juli 2025",
            newsItem2Description: "Wir sind stolz darauf, lokale Gemeinschaften durch unsere neuesten CSR-Initiativen zu unterstützen. Erfahre mehr.",
            readMore: "Mehr lesen",
            viewAllNews: "Alle Nachrichten ansehen",
            aboutHeading: "Über Daheng 4D",
            aboutParagraph1: "Da-Heng 4D ist einer der führenden Lotterie-Anbieter, der sich der Bereitstellung fairer und transparenter Spiele verschrieben hat. Wir engagieren uns für verantwortungsvolles Spielen und tragen durch unsere karitativen Initiativen maßgeblich zum sozialen Wohlergehen bei. Seit unserer Gründung sind wir Teil von Millionen von Träumen und Gewinnergeschichten.",
            aboutParagraph2: "Unser Engagement geht über reine Lotteriespiele hinaus; wir streben danach, einen positiven Einfluss auf die Gesellschaft zu haben, indem wir verschiedene Gemeinschaftsprojekte und Wohlfahrtsorganisationen unterstützen.",
            ourStory: "Unsere Geschichte",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Träume groß, gewinne noch größer!",
            footerQuickLinks: "Schnelllinks",
            navHomeFooter: "Startseite",
            navResultsFooter: "Neueste Ergebnisse",
            navHowToPlayFooter: "Anleitung",
            navNewsFooter: "Nachrichten & Events",
            footerSupport: "Support",
            supportFAQ: "FAQ",
            supportContact: "Kontakt",
            supportGaming: "Verantwortungsvolles Spielen",
            supportPrivacy: "Datenschutzbestimmungen",
            footerContactUs: "Kontakt",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malaysia",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. Alle Rechte vorbehalten. Nur für 18+. Spiele verantwortungsvoll.",
            disclaimer: "Haftungsausschluss: Dies ist eine fiktive Website zu Demonstrationszwecken. Die tatsächlichen Lotterieergebnisse und Informationen können abweichen."
        },
        es: {
            pageTitle: "DAHENG 4D - ¡La mejor lotería, el mejor premio!",
            brandName: "DAHENG 4D",
            navHome: "Inicio",
            navResults: "Resultados",
            navHowToPlay: "Cómo Jugar",
            navPrize: "Premio",
            navAbout: "Acerca de Nosotros",
            navContact: "Contacto",
            heroHeading: "¡Sueña en Grande, Gana en Grande!",
            heroSubheading: "Consulta los últimos resultados de DA-HENG 4D y juega tus números de la suerte hoy mismo.",
            heroHowToPlay: "Cómo Jugar",
            heroLatestResults: "Últimos Resultados",
            resultsHeading: "Resultados Oficiales de DAHENG 4D",
            resultsDescription: "Aquí están los últimos resultados oficiales para el Jueves 18-09-2025 .",
            prizeLabel1: "1er Premio",
            prizeLabel2: "2do Premio",
            prizeLabel3: "3er Premio",
            tableSpecial: "Especial",
            tableConsolation: "Consolación",
            jackpotLabel1: "Bote 4D 1",
            jackpotLabel2: "Bote 4D 2",
            viewPastResults: "Ver Resultados Anteriores",
            nextDrawCountdown: "Cuenta Regresiva para el Próximo Sorteo",
            howToPlayHeading: "Cómo Jugar a Daheng 4D",
            step1Heading: "1. Elige tus Números",
            step1Description: "Selecciona cualquier número de 4 dígitos desde 0000 hasta 9999. También puedes elegir 'Lucky Pick' para un número generado aleatoriamente.",
            step2Heading: "2. Selecciona tu Tipo de Apuesta",
            step2Description: "Elige 'Grande' (permisible, ordinario o suma) o 'Pequeño' (solo permisible) según tu preferencia.",
            step3Heading: "3. Realiza tu Apuesta",
            step3Description: "Decide la cantidad de tu apuesta para cada número elegido y tipo de apuesta. La apuesta mínima es de RM 1.",
            step4Heading: "4. Comprueba los Resultados",
            step4Description: "Los sorteos se celebran tres veces por semana. ¡Vuelve aquí para ver los últimos resultados y descubre si has ganado!",
            learnMore: "Saber Más",
            newsHeading: "Últimas Noticias y Anuncios",
            newsItem1Heading: "¡Próximamente un Nuevo Juego Emocionante!",
            newsItem1Date: "5 de agosto de 2025",
            newsItem1Description: "¡Mantente atento a un anuncio sobre un nuevo juego de lotería con botes aún más grandes!",
            newsItem2Heading: "Programa de Extensión Comunitaria de Daheng",
            newsItem2Date: "28 de julio de 2025",
            newsItem2Description: "Estamos orgullosos de apoyar a las comunidades locales a través de nuestras últimas iniciativas de RSE. Descubre más.",
            readMore: "Leer Más",
            viewAllNews: "Ver Todas las Noticias",
            aboutHeading: "Acerca de Daheng 4D",
            aboutParagraph1: "Da-Heng 4D es uno de los principales operadores de lotería, comprometido a ofrecer juegos justos y transparentes. Nos dedicamos al juego responsable y contribuimos significativamente al bienestar social a través de nuestras iniciativas benéficas. Desde nuestro inicio, hemos sido parte de millones de sueños e historias de ganadores.",
            aboutParagraph2: "Nuestro compromiso se extiende más allá de los juegos de lotería; nos esforzamos por generar un impacto positivo en la sociedad, apoyando diversos proyectos comunitarios y organizaciones de bienestar.",
            ourStory: "Nuestra Historia",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "¡Sueña en Grande, Gana Aún Más Grande!",
            footerQuickLinks: "Enlaces Rápidos",
            navHomeFooter: "Inicio",
            navResultsFooter: "Últimos Resultados",
            navHowToPlayFooter: "Cómo Jugar",
            navNewsFooter: "Noticias y Eventos",
            footerSupport: "Soporte",
            supportFAQ: "FAQ",
            supportContact: "Contacto",
            supportGaming: "Juego Responsable",
            supportPrivacy: "Política de Privacidad",
            footerContactUs: "Contacto",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malasia",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. Todos los derechos reservados. Solo para mayores de 18 años. Juega de forma responsable.",
            disclaimer: "Descargo de responsabilidad: Este es un sitio web ficticio con fines de demostración. Los resultados e información de la lotería real pueden variar."
        },
        ja: {
            pageTitle: "DAHENG 4D - 最高の宝くじ、最高の賞金！",
            brandName: "DAHENG 4D",
            navHome: "ホーム",
            navResults: "結果",
            navHowToPlay: "遊び方",
            navPrize: "賞金",
            navAbout: "私たちについて",
            navContact: "お問い合わせ",
            heroHeading: "大きく夢見て、大きく勝つ！",
            heroSubheading: "最新のDA-HENG 4Dの結果をチェックして、あなたのラッキーナンバーを今日プレイしましょう。",
            heroHowToPlay: "遊び方",
            heroLatestResults: "最新の結果",
            resultsHeading: "DAHENG 4D 公式結果",
            resultsDescription: "2025年9月18日木曜日の最新公式結果はこちらです。",
            prizeLabel1: "1等",
            prizeLabel2: "2等",
            prizeLabel3: "3等",
            tableSpecial: "特別賞",
            tableConsolation: "慰安賞",
            jackpotLabel1: "4Dジャックポット1",
            jackpotLabel2: "4Dジャックポット2",
            viewPastResults: "過去の結果を見る",
            nextDrawCountdown: "次回抽選までのカウントダウン",
            howToPlayHeading: "Daheng 4Dの遊び方",
            step1Heading: "1. 数字を選ぶ",
            step1Description: "0000から9999までの任意の4桁の数字を選びます。ランダムに生成された数字には「ラッキーピック」も選べます。",
            step2Heading: "2. ベットタイプを選ぶ",
            step2Description: "好みに応じて「Big」（許可、通常、または合計）または「Small」（許可のみ）を選びます。",
            step3Heading: "3. ベットする",
            step3Description: "選んだ数字とベットタイプごとにベット額を決めます。最低ベット額はRM 1です。",
            step4Heading: "4. 結果をチェックする",
            step4Description: "抽選は週に3回行われます。最新の結果をここで確認し、あなたが勝ったかどうか見てみましょう！",
            learnMore: "もっと知る",
            newsHeading: "最新ニュースとお知らせ",
            newsItem1Heading: "エキサイティングな新ゲームがまもなく登場！",
            newsItem1Date: "2025年8月5日",
            newsItem1Description: "さらに大きなジャックポットを持つ真新しい宝くじゲームについてのお知らせにご期待ください！",
            newsItem2Heading: "Daheng コミュニティアウトリーチプログラム",
            newsItem2Date: "2025年7月28日",
            newsItem2Description: "最新のCSRイニシアチブを通じて地域社会を支援できることを誇りに思います。詳細をご覧ください。",
            readMore: "もっと読む",
            viewAllNews: "すべてのニュースを見る",
            aboutHeading: "Daheng 4Dについて",
            aboutParagraph1: "Da-Heng 4Dは、公正で透明なゲームを提供することにコミットしている主要な宝くじ運営会社の1つです。私たちは責任あるゲームに専念し、慈善活動を通じて社会福祉に大きく貢献しています。設立以来、私たちは何百万もの夢と勝者の物語の一部となってきました。",
            aboutParagraph2: "私たちのコミットメントは宝くじゲームにとどまりません。私たちは、さまざまな地域プロジェクトや福祉組織を支援することで、社会にポジティブな影響を与えるよう努めています。",
            ourStory: "私たちの物語",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "大きく夢見て、もっと大きく勝つ！",
            footerQuickLinks: "クイックリンク",
            navHomeFooter: "ホーム",
            navResultsFooter: "最新の結果",
            navHowToPlayFooter: "遊び方",
            navNewsFooter: "ニュースとイベント",
            footerSupport: "サポート",
            supportFAQ: "よくある質問",
            supportContact: "お問い合わせ",
            supportGaming: "責任あるゲーム",
            supportPrivacy: "プライバシーポリシー",
            footerContactUs: "お問い合わせ",
            contactAddress: "ロッテリーレーン、クアラルンプール、マレーシア",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. 無断転載を禁じます。18歳以上のみ。責任を持ってプレイしてください。",
            disclaimer: "免責事項：これはデモンストレーション目的の架空のウェブサイトです。実際の宝くじの結果や情報は異なる場合があります。"
        },
        ru: {
            pageTitle: "DAHENG 4D - Лучшая лотерея, лучший приз!",
            brandName: "DAHENG 4D",
            navHome: "Главная",
            navResults: "Результаты",
            navHowToPlay: "Как играть",
            navPrize: "Приз",
            navAbout: "О нас",
            navContact: "Контакты",
            heroHeading: "Мечтай о большом, выигрывай по-крупному!",
            heroSubheading: "Проверьте последние результаты DA-HENG 4D и сыграйте свои счастливые номера сегодня.",
            heroHowToPlay: "Как играть",
            heroLatestResults: "Последние результаты",
            resultsHeading: "Официальные результаты DAHENG 4D",
            resultsDescription: "Здесь представлены последние официальные результаты на четверг 18-09-2025 .",
            prizeLabel1: "1-й приз",
            prizeLabel2: "2-й приз",
            prizeLabel3: "3-й приз",
            tableSpecial: "Специальный",
            tableConsolation: "Утешительный",
            jackpotLabel1: "4D джекпот 1",
            jackpotLabel2: "4D джекпот 2",
            viewPastResults: "Посмотреть прошлые результаты",
            nextDrawCountdown: "Обратный отсчет до следующего тиража",
            howToPlayHeading: "Как играть в Daheng 4D",
            step1Heading: "1. Выберите свои номера",
            step1Description: "Выберите любое 4-значное число от 0000 до 9999. Вы также можете выбрать 'Счастливый выбор' для случайно сгенерированного номера.",
            step2Heading: "2. Выберите тип ставки",
            step2Description: "Выберите 'Большой' (допустимый, обычный или сумма) или 'Малый' (только допустимый) в соответствии с вашими предпочтениями.",
            step3Heading: "3. Сделайте ставку",
            step3Description: "Определите сумму ставки для каждого выбранного номера и типа ставки. Минимальная ставка составляет RM 1.",
            step4Heading: "4. Проверьте результаты",
            step4Description: "Розыгрыши проводятся три раза в неделю. Заходите сюда, чтобы узнать последние результаты и посмотреть, выиграли ли вы!",
            learnMore: "Узнать больше",
            newsHeading: "Последние новости и объявления",
            newsItem1Heading: "Скоро появится новая захватывающая игра!",
            newsItem1Date: "5 августа 2025 года",
            newsItem1Description: "Следите за новостями о совершенно новой лотерейной игре с еще более крупными джекпотами!",
            newsItem2Heading: "Программа Daheng по работе с общественностью",
            newsItem2Date: "28 июля 2025 года",
            newsItem2Description: "Мы гордимся тем, что поддерживаем местные сообщества с помощью наших последних инициатив в области корпоративной социальной ответственности (CSR). Узнайте больше.",
            readMore: "Читать далее",
            viewAllNews: "Посмотреть все новости",
            aboutHeading: "О Daheng 4D",
            aboutParagraph1: "Da-Heng 4D является одним из ведущих лотерейных операторов, приверженным предоставлению честных и прозрачных игр. Мы посвящены ответственной игре и вносим значительный вклад в социальное благополучие через наши благотворительные инициативы. С момента нашего создания мы являемся частью миллионов мечтаний и историй победителей.",
            aboutParagraph2: "Наши обязательства выходят за рамки просто лотерейных игр; мы стремимся оказать положительное влияние на общество, поддерживая различные общественные проекты и благотворительные организации.",
            ourStory: "Наша история",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Мечтай о большом, выигрывай еще больше!",
            footerQuickLinks: "Быстрые ссылки",
            navHomeFooter: "Главная",
            navResultsFooter: "Последние результаты",
            navHowToPlayFooter: "Как играть",
            navNewsFooter: "Новости и события",
            footerSupport: "Поддержка",
            supportFAQ: "FAQ",
            supportContact: "Связаться с нами",
            supportGaming: "Ответственная игра",
            supportPrivacy: "Политика конфиденциальности",
            footerContactUs: "Контакты",
            contactAddress: "Lottery Lane, Куала-Лумпур, Малайзия",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. Все права защищены. Только для 18+. Играйте ответственно.",
            disclaimer: "Отказ от ответственности: это вымышленный веб-сайт для демонстрационных целей. Фактические результаты лотереи и информация могут отличаться."
        },
        fr: {
            pageTitle: "DAHENG 4D - La meilleure loterie, le meilleur prix !",
            brandName: "DAHENG 4D",
            navHome: "Accueil",
            navResults: "Résultats",
            navHowToPlay: "Comment Jouer",
            navPrize: "Prix",
            navAbout: "À Propos de Nous",
            navContact: "Contact",
            heroHeading: "Rêvez Grand, Gagnez Gros !",
            heroSubheading: "Consultez les derniers résultats du 4D DA-HENG et jouez vos numéros chanceux aujourd'hui.",
            heroHowToPlay: "Comment Jouer",
            heroLatestResults: "Derniers Résultats",
            resultsHeading: "Résultats Officiels du DAHENG 4D",
            resultsDescription: "Voici les derniers résultats officiels pour le Jeudi 18-09-2025 .",
            prizeLabel1: "1er Prix",
            prizeLabel2: "2e Prix",
            prizeLabel3: "3e Prix",
            tableSpecial: "Spécial",
            tableConsolation: "Consolation",
            jackpotLabel1: "Jackpot 4D 1",
            jackpotLabel2: "Jackpot 4D 2",
            viewPastResults: "Voir les Résultats Passés",
            nextDrawCountdown: "Compte à rebours du prochain tirage",
            howToPlayHeading: "Comment jouer à Daheng 4D",
            step1Heading: "1. Choisissez vos numéros",
            step1Description: "Sélectionnez n'importe quel numéro à 4 chiffres de 0000 à 9999. Vous pouvez également choisir 'Lucky Pick' pour un numéro généré aléatoirement.",
            step2Heading: "2. Choisissez votre type de pari",
            step2Description: "Choisissez 'Grand' (permis, ordinaire ou somme) ou 'Petit' (uniquement permis) selon votre préférence.",
            step3Heading: "3. Placez votre pari",
            step3Description: "Décidez du montant de votre pari pour chaque numéro choisi et type de pari. Le pari minimum est de 1 RM.",
            step4Heading: "4. Vérifiez les résultats",
            step4Description: "Les tirages ont lieu trois fois par semaine. Revenez ici pour les derniers résultats et voyez si vous avez gagné !",
            learnMore: "En savoir plus",
            newsHeading: "Dernières Nouvelles et Annonces",
            newsItem1Heading: "Un Nouveau Jeu Passionnant Arrive Bientôt !",
            newsItem1Date: "5 août 2025",
            newsItem1Description: "Restez à l'écoute pour une annonce concernant un tout nouveau jeu de loterie avec des jackpots encore plus grands !",
            newsItem2Heading: "Programme de Sensibilisation Communautaire de Daheng",
            newsItem2Date: "28 juillet 2025",
            newsItem2Description: "Nous sommes fiers de soutenir les communautés locales grâce à nos dernières initiatives de RSE. En savoir plus.",
            readMore: "Lire la suite",
            viewAllNews: "Voir toutes les nouvelles",
            aboutHeading: "À propos de Daheng 4D",
            aboutParagraph1: "Da-Heng 4D est l'un des principaux opérateurs de loterie, engagé à fournir des jeux équitables et transparents. Nous nous dédions au jeu responsable et contribuons de manière significative au bien-être social à travers nos initiatives caritatives. Depuis notre création, nous avons fait partie de millions de rêves et d'histoires de gagnants.",
            aboutParagraph2: "Notre engagement s'étend au-delà des simples jeux de loterie ; nous nous efforçons d'avoir un impact positif sur la société, en soutenant divers projets communautaires et organisations de bien-être.",
            ourStory: "Notre Histoire",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Rêvez Grand, Gagnez Encore Plus Grand !",
            footerQuickLinks: "Liens Rapides",
            navHomeFooter: "Accueil",
            navResultsFooter: "Derniers Résultats",
            navHowToPlayFooter: "Comment Jouer",
            navNewsFooter: "Nouvelles et Événements",
            footerSupport: "Soutien",
            supportFAQ: "FAQ",
            supportContact: "Contactez-nous",
            supportGaming: "Jeu Responsable",
            supportPrivacy: "Politique de Confidentialité",
            footerContactUs: "Contactez-nous",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malaisie",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. Tous droits réservés. Pour les 18+ seulement. Jouez de manière responsable.",
            disclaimer: "Avertissement : Ceci est un site web fictif à des fins de démonstration. Les résultats et informations de loterie réels peuvent varier."
        },
        vi: {
            pageTitle: "DAHENG 4D - Xổ số tốt nhất, giải thưởng tốt nhất!",
            brandName: "DAHENG 4D",
            navHome: "Trang chủ",
            navResults: "Kết quả",
            navHowToPlay: "Cách chơi",
            navPrize: "Giải thưởng",
            navAbout: "Về chúng tôi",
            navContact: "Liên hệ",
            heroHeading: "Mơ lớn, thắng lớn!",
            heroSubheading: "Kiểm tra kết quả 4D DA-HENG mới nhất và chơi những con số may mắn của bạn ngay hôm nay.",
            heroHowToPlay: "Cách chơi",
            heroLatestResults: "Kết quả mới nhất",
            resultsHeading: "Kết quả DAHENG 4D chính thức",
            resultsDescription: "Dưới đây là kết quả chính thức mới nhất cho Thứ Năm 18-09-2025 .",
            prizeLabel1: "Giải nhất",
            prizeLabel2: "Giải nhì",
            prizeLabel3: "Giải ba",
            tableSpecial: "Giải đặc biệt",
            tableConsolation: "Giải khuyến khích",
            jackpotLabel1: "Jackpot 4D 1",
            jackpotLabel2: "Jackpot 4D 2",
            viewPastResults: "Xem kết quả cũ",
            nextDrawCountdown: "Đếm ngược đến lượt quay số tiếp theo",
            howToPlayHeading: "Cách chơi Daheng 4D",
            step1Heading: "1. Chọn số của bạn",
            step1Description: "Chọn bất kỳ số 4 chữ số nào từ 0000 đến 9999. Bạn cũng có thể chọn 'Lucky Pick' để có một số ngẫu nhiên.",
            step2Heading: "2. Chọn loại cược của bạn",
            step2Description: "Chọn 'Lớn' (được phép, bình thường hoặc tổng) hoặc 'Nhỏ' (chỉ được phép) tùy theo sở thích của bạn.",
            step3Heading: "3. Đặt cược của bạn",
            step3Description: "Quyết định số tiền cược của bạn cho mỗi số đã chọn và loại cược. Cược tối thiểu là 1 RM.",
            step4Heading: "4. Kiểm tra kết quả",
            step4Description: "Các lượt quay số được tổ chức ba lần một tuần. Quay lại đây để xem kết quả mới nhất và xem bạn đã thắng chưa!",
            learnMore: "Tìm hiểu thêm",
            newsHeading: "Tin tức & Thông báo mới nhất",
            newsItem1Heading: "Trò chơi mới hấp dẫn sắp ra mắt!",
            newsItem1Date: "Ngày 5 tháng 8 năm 2025",
            newsItem1Description: "Hãy theo dõi thông báo về một trò chơi xổ số hoàn toàn mới với các giải độc đắc lớn hơn nữa!",
            newsItem2Heading: "Chương trình tiếp cận cộng đồng Daheng",
            newsItem2Date: "Ngày 28 tháng 7 năm 2025",
            newsItem2Description: "Chúng tôi tự hào hỗ trợ các cộng đồng địa phương thông qua các sáng kiến CSR mới nhất của chúng tôi. Tìm hiểu thêm.",
            readMore: "Đọc thêm",
            viewAllNews: "Xem tất cả tin tức",
            aboutHeading: "Về Daheng 4D",
            aboutParagraph1: "Da-Heng 4D là một trong những nhà điều hành xổ số hàng đầu, cam kết cung cấp các trò chơi công bằng và minh bạch. Chúng tôi tận tâm với việc chơi game có trách nhiệm và đóng góp đáng kể vào phúc lợi xã hội thông qua các sáng kiến từ thiện của mình. Kể từ khi thành lập, chúng tôi đã là một phần của hàng triệu giấc mơ và câu chuyện của những người chiến thắng.",
            aboutParagraph2: "Cam kết của chúng tôi vượt ra ngoài các trò chơi xổ số; chúng tôi cố gắng tạo ra tác động tích cực đến xã hội, hỗ trợ các dự án cộng đồng và các tổ chức phúc lợi khác nhau.",
            ourStory: "Câu chuyện của chúng tôi",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "Mơ lớn, thắng lớn hơn!",
            footerQuickLinks: "Liên kết nhanh",
            navHomeFooter: "Trang chủ",
            navResultsFooter: "Kết quả mới nhất",
            navHowToPlayFooter: "Cách chơi",
            navNewsFooter: "Tin tức & Sự kiện",
            footerSupport: "Hỗ trợ",
            supportFAQ: "Câu hỏi thường gặp",
            supportContact: "Liên hệ chúng tôi",
            supportGaming: "Chơi game có trách nhiệm",
            supportPrivacy: "Chính sách bảo mật",
            footerContactUs: "Liên hệ chúng tôi",
            contactAddress: "Lottery Lane, Kuala Lumpur, Malaysia",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. Đã đăng ký Bản quyền. Chỉ dành cho 18+. Chơi có trách nhiệm.",
            disclaimer: "Tuyên bố từ chối trách nhiệm: Đây là một trang web hư cấu cho mục đích trình diễn. Kết quả và thông tin xổ số thực tế có thể thay đổi."
        },
        ko: {
            pageTitle: "DAHENG 4D - 최고의 복권 최고의 상금!",
            brandName: "DAHENG 4D",
            navHome: "홈",
            navResults: "결과",
            navHowToPlay: "게임 방법",
            navPrize: "상금",
            navAbout: "회사 소개",
            navContact: "연락처",
            heroHeading: "크게 꿈꾸고, 크게 승리하세요!",
            heroSubheading: "최신 DA-HENG 4D 결과를 확인하고 오늘 당신의 행운 번호를 플레이하세요.",
            heroHowToPlay: "게임 방법",
            heroLatestResults: "최신 결과",
            resultsHeading: "공식 DAHENG 4D 결과",
            resultsDescription: "2025년 9월 18일 목요일의 최신 공식 결과입니다.",
            prizeLabel1: "1등 상금",
            prizeLabel2: "2등 상금",
            prizeLabel3: "3등 상금",
            tableSpecial: "특별",
            tableConsolation: "위로",
            jackpotLabel1: "4D 잭팟 1",
            jackpotLabel2: "4D 잭팟 2",
            viewPastResults: "과거 결과 보기",
            nextDrawCountdown: "다음 추첨 카운트다운",
            howToPlayHeading: "Daheng 4D 게임 방법",
            step1Heading: "1. 번호 선택",
            step1Description: "0000부터 9999까지의 4자리 숫자 중 아무거나 선택하세요. 무작위로 생성된 번호를 위해 '럭키 픽'을 선택할 수도 있습니다.",
            step2Heading: "2. 베팅 유형 선택",
            step2Description: "선호도에 따라 '크게'(허용, 일반 또는 합계) 또는 '작게'(허용만)를 선택하세요.",
            step3Heading: "3. 베팅하기",
            step3Description: "선택한 각 번호와 베팅 유형에 대한 베팅 금액을 결정하세요. 최소 베팅 금액은 RM 1입니다.",
            step4Heading: "4. 결과 확인",
            step4Description: "추첨은 일주일에 세 번 개최됩니다. 최신 결과를 확인하고 당신이 이겼는지 확인하세요!",
            learnMore: "더 알아보기",
            newsHeading: "최신 뉴스 및 공지사항",
            newsItem1Heading: "흥미로운 새 게임이 곧 출시됩니다!",
            newsItem1Date: "2025년 8월 5일",
            newsItem1Description: "더 큰 잭팟이 있는 새로운 복권 게임에 대한 발표를 계속 지켜봐 주세요!",
            newsItem2Heading: "Daheng 지역사회 봉사 프로그램",
            newsItem2Date: "2025년 7월 28일",
            newsItem2Description: "우리의 최신 CSR 이니셔티브를 통해 지역 사회를 지원하게 된 것을 자랑스럽게 생각합니다. 더 알아보기.",
            readMore: "더 읽기",
            viewAllNews: "모든 뉴스 보기",
            aboutHeading: "Daheng 4D 소개",
            aboutParagraph1: "Da-Heng 4D는 공정하고 투명한 게임을 제공하기 위해 노력하는 선도적인 복권 운영자 중 하나입니다. 우리는 책임감 있는 게임에 전념하고 자선 활동을 통해 사회 복지에 크게 기여하고 있습니다. 설립 이래, 우리는 수백만 명의 꿈과 승자의 이야기의 일부가 되어왔습니다.",
            aboutParagraph2: "우리의 약속은 단순히 복권 게임을 넘어섭니다; 우리는 다양한 지역사회 프로젝트와 복지 단체를 지원함으로써 사회에 긍정적인 영향을 미치기 위해 노력합니다.",
            ourStory: "우리의 이야기",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "크게 꿈꾸고, 더 크게 승리하세요!",
            footerQuickLinks: "빠른 링크",
            navHomeFooter: "홈",
            navResultsFooter: "최신 결과",
            navHowToPlayFooter: "게임 방법",
            navNewsFooter: "뉴스 및 이벤트",
            footerSupport: "지원",
            supportFAQ: "FAQ",
            supportContact: "문의하기",
            supportGaming: "책임감 있는 게임",
            supportPrivacy: "개인정보 보호정책",
            footerContactUs: "문의하기",
            contactAddress: "로터리 레인, 쿠알라룸푸르, 말레이시아",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. 모든 권리 보유. 18세 이상만. 책임감 있게 게임하세요.",
            disclaimer: "면책 조항: 이 웹사이트는 데모 목적으로 만들어진 가상의 웹사이트입니다. 실제 복권 결과 및 정보는 다를 수 있습니다."
        },
        bn: {
            pageTitle: "DAHENG 4D - সেরা লটারি সেরা পুরস্কার!",
            brandName: "DAHENG 4D",
            navHome: "হোম",
            navResults: "ফলাফল",
            navHowToPlay: "কিভাবে খেলবেন",
            navPrize: "পুরস্কার",
            navAbout: "আমাদের সম্পর্কে",
            navContact: "যোগাযোগ",
            heroHeading: "বড় স্বপ্ন দেখুন, বড় জিতুন!",
            heroSubheading: "সর্বশেষ DA-HENG 4D ফলাফলগুলি দেখুন এবং আজই আপনার ভাগ্যবান নম্বর খেলুন।",
            heroHowToPlay: "কিভাবে খেলবেন",
            heroLatestResults: "সর্বশেষ ফলাফল",
            resultsHeading: "অফিশিয়াল DAHENG 4D ফলাফল",
            resultsDescription: "বৃহস্পতিবার 18-09-2025  এর সর্বশেষ অফিসিয়াল ফলাফল এখানে দেওয়া হলো।",
            prizeLabel1: "১ম পুরস্কার",
            prizeLabel2: "২য় পুরস্কার",
            prizeLabel3: "৩য় পুরস্কার",
            tableSpecial: "বিশেষ",
            tableConsolation: "সান্ত্বনা",
            jackpotLabel1: "4D জ্যাকপট 1",
            jackpotLabel2: "4D জ্যাকপট 2",
            viewPastResults: "আগের ফলাফল দেখুন",
            nextDrawCountdown: "পরবর্তী ড্র কাউন্টডাউন",
            howToPlayHeading: "Daheng 4D কিভাবে খেলবেন",
            step1Heading: "1. আপনার নম্বরগুলি বেছে নিন",
            step1Description: "0000 থেকে 9999 পর্যন্ত যেকোনো 4-সংখ্যার নম্বর বেছে নিন। আপনি একটি এলোমেলোভাবে তৈরি নম্বরের জন্য 'লাকি পিক'ও বেছে নিতে পারেন।",
            step2Heading: "2. আপনার বাজি ধরন নির্বাচন করুন",
            step2Description: "আপনার পছন্দ অনুযায়ী 'বড়' (অনুমতিযোগ্য, সাধারণ, বা যোগফল) বা 'ছোট' (কেবলমাত্র অনুমতিযোগ্য) বেছে নিন।",
            step3Heading: "3. আপনার বাজি রাখুন",
            step3Description: "প্রতিটি নির্বাচিত নম্বর এবং বাজির ধরনের জন্য আপনার বাজির পরিমাণ নির্ধারণ করুন। সর্বনিম্ন বাজি হল RM 1।",
            step4Heading: "4. ফলাফলগুলি দেখুন",
            step4Description: "সপ্তাহে তিনবার ড্র অনুষ্ঠিত হয়। সর্বশেষ ফলাফলের জন্য এখানে ফিরে আসুন এবং দেখুন আপনি জিতেছেন কিনা!",
            learnMore: "আরও জানুন",
            newsHeading: "সর্বশেষ খবর ও ঘোষণা",
            newsItem1Heading: "শীঘ্রই আসছে একটি উত্তেজনাপূর্ণ নতুন খেলা!",
            newsItem1Date: "5 আগস্ট, 2025",
            newsItem1Description: "আরও বড় জ্যাকপট সহ একটি নতুন লটারি খেলা সম্পর্কে ঘোষণার জন্য সাথে থাকুন!",
            newsItem2Heading: "দা হেং কমিউনিটি আউটরিচ প্রোগ্রাম",
            newsItem2Date: "28 জুলাই, 2025",
            newsItem2Description: "আমরা আমাদের সর্বশেষ সিএসআর উদ্যোগের মাধ্যমে স্থানীয় সম্প্রদায়গুলিকে সমর্থন করতে পেরে গর্বিত। আরও জানুন।",
            readMore: "আরও পড়ুন",
            viewAllNews: "সব খবর দেখুন",
            aboutHeading: "Daheng 4D সম্পর্কে",
            aboutParagraph1: "Da-Heng 4D হল একটি নেতৃস্থানীয় লটারি অপারেটর, যা ন্যায্য এবং স্বচ্ছ গেম সরবরাহে প্রতিশ্রুতিবদ্ধ। আমরা দায়িত্বশীল গেমিংয়ের জন্য নিবেদিত এবং আমাদের দাতব্য উদ্যোগের মাধ্যমে সামাজিক কল্যাণে উল্লেখযোগ্য অবদান রাখি। আমাদের শুরু থেকে, আমরা লক্ষ লক্ষ স্বপ্ন এবং বিজয়ীর গল্পের অংশ হয়েছি।",
            aboutParagraph2: "আমাদের প্রতিশ্রুতি শুধুমাত্র লটারি গেমের বাইরেও প্রসারিত; আমরা বিভিন্ন সম্প্রদায়ের প্রকল্প এবং কল্যাণ সংস্থাকে সমর্থন করে সমাজে একটি ইতিবাচক প্রভাব ফেলতে চেষ্টা করি।",
            ourStory: "আমাদের গল্প",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "বড় স্বপ্ন দেখুন, আরও বড় জিতুন!",
            footerQuickLinks: "দ্রুত লিংক",
            navHomeFooter: "হোম",
            navResultsFooter: "সর্বশেষ ফলাফল",
            navHowToPlayFooter: "কিভাবে খেলবেন",
            navNewsFooter: "খবর ও ঘটনা",
            footerSupport: "সহায়তা",
            supportFAQ: "প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী",
            supportContact: "আমাদের সাথে যোগাযোগ করুন",
            supportGaming: "দায়িত্বশীল গেমিং",
            supportPrivacy: "গোপনীয়তা নীতি",
            footerContactUs: "আমাদের সাথে যোগাযোগ করুন",
            contactAddress: "লটারি লেন, কুয়ালালামপুর, মালয়েশিয়া",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. সর্বস্বত্ব সংরক্ষিত। শুধুমাত্র 18+ এর জন্য। দায়িত্বের সাথে খেলুন।",
            disclaimer: "দাবি অস্বীকার: এটি প্রদর্শনের উদ্দেশ্যে একটি কাল্পনিক ওয়েবসাইট। প্রকৃত লটারির ফলাফল এবং তথ্য পরিবর্তিত হতে পারে।"
        },
        ar: {
            pageTitle: "DAHENG 4D - أفضل يانصيب، أفضل جائزة!",
            brandName: "DAHENG 4D",
            navHome: "الرئيسية",
            navResults: "النتائج",
            navHowToPlay: "كيفية اللعب",
            navPrize: "الجائزة",
            navAbout: "نبذة عنا",
            navContact: "اتصل بنا",
            heroHeading: "احلم كبيرًا، اربح كبيرًا!",
            heroSubheading: "تحقق من أحدث نتائج DA-HENG 4D والعب أرقامك المحظوظة اليوم.",
            heroHowToPlay: "كيفية اللعب",
            heroLatestResults: "أحدث النتائج",
            resultsHeading: "نتائج DAHENG 4D الرسمية",
            resultsDescription: "هنا أحدث النتائج الرسمية ليوم الخميس 18-09-2025 .",
            prizeLabel1: "الجائزة الأولى",
            prizeLabel2: "الجائزة الثانية",
            prizeLabel3: "الجائزة الثالثة",
            tableSpecial: "خاص",
            tableConsolation: "ترويحية",
            jackpotLabel1: "الرهان الكبير 4D 1",
            jackpotLabel2: "الرهان الكبير 4D 2",
            viewPastResults: "عرض النتائج السابقة",
            nextDrawCountdown: "العد التنازلي للسحب التالي",
            howToPlayHeading: "كيفية لعب Daheng 4D",
            step1Heading: "1. اختر أرقامك",
            step1Description: "اختر أي رقم مكون من 4 أرقام من 0000 إلى 9999. يمكنك أيضًا اختيار 'Lucky Pick' لرقم يتم إنشاؤه عشوائيًا.",
            step2Heading: "2. حدد نوع رهانك",
            step2Description: "اختر 'كبير' (مسموح، عادي، أو مجموع) أو 'صغير' (مسموح فقط) وفقًا لتفضيلك.",
            step3Heading: "3. ضع رهانك",
            step3Description: "حدد مبلغ رهانك لكل رقم ونوع رهان مختار. الحد الأدنى للرهان هو 1 رينغيت ماليزي.",
            step4Heading: "4. تحقق من النتائج",
            step4Description: "تُجرى السحوبات ثلاث مرات في الأسبوع. عُد إلى هنا للاطلاع على أحدث النتائج ومعرفة ما إذا كنت قد فزت!",
            learnMore: "تعرف على المزيد",
            newsHeading: "أحدث الأخبار والإعلانات",
            newsItem1Heading: "لعبة جديدة مثيرة قادمة قريبًا!",
            newsItem1Date: "5 أغسطس 2025",
            newsItem1Description: "ترقبوا إعلانًا عن لعبة يانصيب جديدة تمامًا بجوائز كبرى أكبر!",
            newsItem2Heading: "برنامج Daheng للتواصل المجتمعي",
            newsItem2Date: "28 يوليو 2025",
            newsItem2Description: "نحن فخورون بدعم المجتمعات المحلية من خلال أحدث مبادراتنا في مجال المسؤولية الاجتماعية للشركات. اكتشف المزيد.",
            readMore: "اقرأ المزيد",
            viewAllNews: "عرض كل الأخبار",
            aboutHeading: "نبذة عن Daheng 4D",
            aboutParagraph1: "Da-Heng 4D هو أحد مشغلي اليانصيب الرائدين، الملتزمين بتقديم ألعاب عادلة وشفافة. نحن ملتزمون بالألعاب المسؤولة ونساهم بشكل كبير في الرفاهية الاجتماعية من خلال مبادراتنا الخيرية. منذ بدايتنا، كنا جزءًا من ملايين الأحلام وقصص الفائزين.",
            aboutParagraph2: "يمتد التزامنا إلى ما هو أبعد من مجرد ألعاب اليانصيب؛ نحن نسعى جاهدين لإحداث تأثير إيجابي على المجتمع، من خلال دعم المشاريع المجتمعية المختلفة ومنظمات الرفاهية.",
            ourStory: "قصتنا",
            brandNameFooter: "DAHENG 4D",
            footerTagline: "احلم كبيرًا، اربح أكبر!",
            footerQuickLinks: "روابط سريعة",
            navHomeFooter: "الرئيسية",
            navResultsFooter: "أحدث النتائج",
            navHowToPlayFooter: "كيفية اللعب",
            navNewsFooter: "أخبار وفعاليات",
            footerSupport: "الدعم",
            supportFAQ: "الأسئلة الشائعة",
            supportContact: "اتصل بنا",
            supportGaming: "الألعاب المسؤولة",
            supportPrivacy: "سياسة الخصوصية",
            footerContactUs: "اتصل بنا",
            contactAddress: "Lottery Lane, كوالالمبور، ماليزيا",
            contactEmail: "info@daheng4d.my",
            copyright: "© 2025 DAHENG 4D. جميع الحقوق محفوظة. للبالغين 18+ فقط. العب بمسؤولية.",
            disclaimer: "إخلاء مسؤولية: هذا موقع ويب وهمي لأغراض العرض التوضيحي. قد تختلف نتائج اليانصيب الفعلية والمعلومات."
        }
    };

    // --- NEW: FUNCTION TO UPDATE TEXT BASED ON LANGUAGE ---
    function setLanguage(lang) {
        const elements = document.querySelectorAll('[data-i18n]');
        elements.forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[lang] && translations[lang][key]) {
                el.textContent = translations[lang][key];
            }
        });

        // Handle special cases that aren't simple textContent updates
        document.title = translations[lang].pageTitle;

        // Special case for results description which includes variables
        const currentDrawDate = document.querySelector('.draw-date').textContent;
        const currentDrawNo = document.querySelector('.draw-no').textContent;
        if (lang === 'en') {
            document.querySelector('.results-main-section .section-description').textContent = `Here are the latest official results for ${currentDrawDate} .`;
        } else if (lang === 'ms') {
            document.querySelector('.results-main-section .section-description').textContent = `Berikut adalah keputusan rasmi terkini untuk ${currentDrawDate} .`;
        } else if (lang === 'zh') {
            document.querySelector('.results-main-section .section-description').textContent = `Berikut adalah keputusan rasmi terkini untuk ${currentDrawDate} .`;
        } else if (lang === 'fzh') {
            document.querySelector('.results-main-section .section-description').textContent = `以下是${currentDrawDate}的最新官方开彩成绩。`;
        } else if (lang === 'th') {
            document.querySelector('.results-main-section .section-description').textContent = `นี่คือผลอย่างเป็นทางการล่าสุดสำหรับ${currentDrawDate} 。`;
        } else if (lang === 'fil') {
            document.querySelector('.results-main-section .section-description').textContent = `Narito ang pinakabagong mga opisyal na resulta para sa ${currentDrawDate} .`;
        } else if (lang === 'id') {
            document.querySelector('.results-main-section .section-description').textContent = `Berikut adalah hasil resmi terbaru untuk ${currentDrawDate} .`;
        } else if (lang === 'ta') {
            document.querySelector('.results-main-section .section-description').textContent = `${currentDrawDate}  க்கான சமீபத்திய அதிகாரப்பூர்வ முடிவுகள் இங்கே உள்ளன.`;
        } else if (lang === 'hi') {
            document.querySelector('.results-main-section .section-description').textContent = `गुरुवार ${currentDrawDate}  के नवीनतम आधिकारिक परिणाम यहाँ दिए गए हैं।`;
        } else if (lang === 'de') {
            document.querySelector('.results-main-section .section-description').textContent = `Hier sind die neuesten offiziellen Ergebnisse für ${currentDrawDate} .`;
        } else if (lang === 'es') {
            document.querySelector('.results-main-section .section-description').textContent = `Aquí están los últimos resultados oficiales para el ${currentDrawDate} .`;
        } else if (lang === 'ja') {
            document.querySelector('.results-main-section .section-description').textContent = `${currentDrawDate}の最新公式結果はこちらです。`;
        } else if (lang === 'ru') {
            document.querySelector('.results-main-section .section-description').textContent = `Здесь представлены последние официальные результаты на ${currentDrawDate} .`;
        } else if (lang === 'fr') {
            document.querySelector('.results-main-section .section-description').textContent = `Voici les derniers résultats officiels pour le ${currentDrawDate} .`;
        } else if (lang === 'vi') {
            document.querySelector('.results-main-section .section-description').textContent = `Dưới đây là kết quả chính thức mới nhất cho ${currentDrawDate} .`;
        } else if (lang === 'ko') {
            document.querySelector('.results-main-section .section-description').textContent = `${currentDrawDate}의 최신 공식 결과입니다.`;
        } else if (lang === 'bn') {
            document.querySelector('.results-main-section .section-description').textContent = `বৃহস্পতিবার ${currentDrawDate} এর সর্বশেষ অফিসিয়াল ফলাফল এখানে দেওয়া হলো।`;
        } else if (lang === 'ar') {
            document.querySelector('.results-main-section .section-description').textContent = `هنا أحدث النتائج الرسمية ليوم ${currentDrawDate} .`;
        }
    }

    // --- NEW: LANGUAGE SWITCHER EVENT LISTENER ---
    const langSelect = document.getElementById('lang-select');
    if (langSelect) {
        langSelect.addEventListener('change', (event) => {
            setLanguage(event.target.value);
            // Save user preference to local storage
            localStorage.setItem('lang', event.target.value);
        });
    }

    // --- INITIALIZE THE PAGE WITH THE DEFAULT LANGUAGE ---
    const userPreferredLang = localStorage.getItem('lang') || 'en';
    if (langSelect) {
        langSelect.value = userPreferredLang;
    }
    setLanguage(userPreferredLang);

    // --- CALL THIS FUNCTION TO SCHEDULE YOUR NEXT DRAW ---
    scheduleNextResult(21, 0, 0); // 9 PM
});
